Extension: Ethnicity
Id: ethnicity
Description: "The ethnicity of the patient. One to six level 4 codes."
//These files were generated by a script from a model at NzNHIPatient.ethnicity

* extension 0..0
* value[x] only CodeableConcept
* valueCodeableConcept from https://standards.digital.health.nz/fhir/ValueSet/ethnicity (preferred)