Extension: Patient_iwi
Id: patient-iwi
Description: "Details related to maori ancestry"
//These files were generated by a script from a model at NzNHIPatient.iwi

* extension 0..0
* value[x] only CodeableConcept
* valueCodeableConcept from http://standards.digital.health.nz/fhir/ValueSet/nziwi (preferred)