Extension: Patient_maoriDescent
Id: patient-maoriDescent
Description: "Is the person of maori descent - yes, no, unknown, notanswered"
//These files were generated by a script from a model at NzNHIPatient.maoriDescent

* extension 0..0
* value[x] only CodeableConcept
* valueCodeableConcept from http://standards.digital.health.nz/fhir/ValueSet/nzmaoridescent (preferred)