Extension: Dhb
Id: dhb
Description: "The District Health Board the patient resides in. It is derived from the patient's primary residential address. Not updated directly."
//These files were generated by a script from a model at NzNHIPatient.DHB

* extension 0..0
* value[x] only CodeableConcept
* valueCodeableConcept from https://standards.digital.health.nz/fhir/ValueSet/dhb (preferred)