Extension: BuildingName
Id: buildingName
Description: "No description"
//These files were generated by a script from a model at NzNHIPatient.address.buildingName

* extension 0..0
* value[x] only string