Extension: NotValidatedReason
Id: notValidatedReason
Description: "The reason why the address has not been validated"
//These files were generated by a script from a model at NzNHIPatient.address.notValidatedReason

* extension 0..0
* value[x] only CodeableConcept
* valueCodeableConcept from https://standards.digital.health.nz/fhir/ValueSet/addressnotvalidatedreason (preferred)