Extension: Suburb
Id: suburb
Description: "The suburb of the address. This is not the same as 'district' or 'state."
//These files were generated by a script from a model at NzNHIPatient.address.suburb

* extension 0..0
* value[x] only string