Extension: OriginalValue
Id: originalValue
Description: "when 'other'; was specified in a form this is what they said"
//These files were generated by a script from a model at NzNHIPatient.gender.responseText

* extension 0..0
* value[x] only string