#!/usr/bin/env node

/**
 * Upload the resources generated by sushi, except for SD's. Actually, this could be for all resources (including SD's) - need to think about that...
 */

let IG = require("./IGUtils")
IG.loadIG('nzRegistry.json')

console.log("Uploading resources that are not StructureDefinitions")



let fs = require('fs');
let syncRequest = require('sync-request');
let serverRoot = "http://home.clinfhir.com:8054/baseR4/"

let path = '../shorthand/build/input/resources/';       //where the files are located

fs.readdirSync(path).forEach(function(file) {
    let ar = file.split('-')
    if (ar.length > 1) {

        let type = ar[0];
        if (type !== 'StructureDefinition') {       //?? really exclude these? could remove from uploadProfileFSH
            let fullFileName = path + file;     //location of the fsh file
            
            //create a Binary resource and upload to the server
            let contents = fs.readFileSync(fullFileName, {encoding: 'utf8'})

        
            let resource = JSON.parse(contents)
            resource.fhirVersion = "4.0.0"; //temp - the FHIR server I'm using for this doesn't support 4.0.1 ...

            let url = serverRoot + type + "/" + resource.id; 
           
            IG.PUTFile(url,resource)

            //now see if the resource is in the IG
            let vo = {reference:resource.resourceType + '/' + resource.id}
            IG.updateIG(vo)
        }

}

})




//PUT a file to the server, given url and contents
function PUTFileDEP(url,resource) {

    console.log(url);
    var options = {};
    options.headers = {"content-type": "application/json+fhir"}
    options.timeout = 20000;        //20 seconds
    options.body = JSON.stringify(resource);

    var response = syncRequest('PUT', url, options);
    console.log(response.statusCode)
    if (response.statusCode !== 200 && response.statusCode !== 201) {
        console.log('  error' + response.body.toString())
        return false
    } else {
        if (response.statusCode == 200) {
            console.log('Updated ' + url)
        } 
        
        if (response.statusCode == 201) {
            console.log('Created ' + url)
        }
       
        return true
    }
}